### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by lpr70**
Replaced the Group section with a description.
Updated the Core feature section.

### CODE REVIEW

**Comment by lmd414** [comment]
Looks good! This is exactly what we discussed in the meeting.

**Comment by justin-russell** [comment]
Looks good, thanks!

**Comment by mcPython04** [comment]
> Replaced the Group section with a description.
> Updated the Core feature section.

**Comment by mcPython04** [comment]
Looks good, we defin

**Comment by mcPython04** [comment]
Looks good, we definitely need that description of our project.

**Pull request merged**
